version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: ${POSTGRES_DB}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  app: 
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: sh -c "npx typeorm -d dist/db/data-source.js migration:run; npm run start:dev"
    depends_on:
      - db